{
    "name": "Кабошоны: база",
    "summary": "Базовые справочники и поля товаров для учета кабошонов",
    "version": "19.0.1.0.0",
    "category": "Inventory/Inventory",
    "author": "Cabochon Ware",
    "license": "LGPL-3",
    "depends": [
        "base",
        "mail",
        "product",
        "stock",
    ],
    "data": [
        "security/cabochon_groups.xml",
        "security/ir.model.access.csv",
        "security/cabochon_activity_rules.xml",
        "data/cabochon_reference_data.xml",
        "views/cabochon_menus.xml",
        "views/audit_log_views.xml",
        "views/cabochon_reference_views.xml",
        "views/product_template_views.xml",
    ],
    "application": True,
    "installable": True,
}
